name: Bare Run on various PHP versions

on:
    push:
        branches:
            - 'main'

jobs:
    bare_run:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                php_version: ['7.2', '8.4']

        steps:
            -   uses: actions/checkout@v2

            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php_version }}
                    coverage: none

            -   run: mkdir nested-dir


            -   run: composer require symplify/config-transformer --dev --ansi
                working-directory: nested-dir

            -   run: vendor/bin/config-transformer -h --ansi
                working-directory: nested-dir
